spring:
  application:
    name: authentication-example

  # encoding
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  # dbms
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: final_project
    password: qwer1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  # Spring Security
  security:
    user:
      name:
      password: 1

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

